---
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - vars.yml
  environment:
    AWS_REGION: "{{ region }}"

  tasks:

    - name: launch cloudformation
      cloudformation:
        stack_name: "static-web-{{ s3_static_site_bucket }}"
        state: "present"
        disable_rollback: false
        template: "cicd/cloudformation/S3_Website.template"
        template_parameters:
          S3BucketName: "{{ s3_static_site_bucket }}"