---
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - vars.yml
  environment:
    AWS_REGION: "{{ region }}"
    AWS_EB_PROFILE: "{{ aws_profile }}"


  tasks:

  - name: Create Elastic Beanstalk application
    shell: "eb init -y"
    args:
        chdir: ../../

  - name: Create Elastic Beanstalk environment
    shell: "eb create {{ env_name }} --cfg {{ env_name }}"
    args:
        chdir: ../../

  - debug: var=output.stdout_lines

  - name: Deploy Elastic Beanstalk application to environment
    shell: "eb deploy {{ env_name }}"
    args:
        chdir: ../../



