---
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - vars.yml
  environment:
    AWS_REGION: "{{ region }}"
    AWS_EB_PROFILE: "{{ aws_profile }}"


# Create & Deploy Static site and application
- include: create_static_site.yml
- include: create_eb_env.yml