---
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - vars.yml
  environment:
    AWS_REGION: "{{ region }}"

  tasks:
    - name: launch cloudformation
      shell: "aws s3 cp src/main/webapp/static s3://{{ s3_static_site_bucket }}/static --recursive"