---
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - vars.yml
  environment:
    AWS_REGION: "{{ region }}"
    AWS_EB_PROFILE: "{{ aws_profile }}"

# Deploy Static site and application
- include: deploy_static_site.yml
- include: deploy_eb_app.yml