---
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - vars.yml
  environment:
    AWS_REGION: "{{ region }}"
    AWS_EB_PROFILE: "{{ aws_profile }}"

  tasks:

  - name: Deploy Elastic Beanstalk application
    shell: "eb deploy {{ env_name }}"
    args:
      chdir: ../../


